---
title: "Data visualization"
author: "Laura Linnea Määttä"
date: "17/6/2021"
output: html_document
---
```{r setup}
# Load packages
source(here::here("R/package_loading.R"))

# Load tidied data
load(here::here("data/nhanes_small.rda"))
```

# One variable plots

```{r continuous-variables}

# OBS, normally, each plot should have its own code chunk

# Density plot
ggplot(nhanes_small, aes(x = bmi)) + 
           geom_density()

# Histogram
ggplot(nhanes_small, aes(x = bmi)) + 
    geom_histogram()

```

```{r discrete-variables}

# Barplot 
ggplot(nhanes_small, aes(x = sex)) +
    geom_bar()

ggplot(nhanes_small, aes(x = diabetes)) +
    geom_bar()


```


```{r remove-missing-diabates}

# Remove diabetes NA values
nhanes_tidied <- nhanes_small %>% 
    filter(!is.na(diabetes))
summary(nhanes_tidied)

# Save tidied data-set
usethis::use_data(nhanes_tidied, overwrite = T) # overwrite = T overwrites the nhanes_tidied everytime the script is run 

# Barplot witout the missing diabetes cases
ggplot(nhanes_tidied, aes(x = diabetes)) +
    geom_bar()


```

# Two variable plots

```{r two-continuous-variables}

# Save the plot "base" in a object to make further plotting easier
bmi_chol <- ggplot(nhanes_tidied, aes(x = bmi, y = tot_chol))

# Scatter plot
bmi_chol + geom_point()

# Scatter plot with density 
bmi_chol + geom_hex()

# Smoothing line with confidence interval 
bmi_chol + geom_smooth()


# Combining layers of geoms 
bmi_chol + geom_hex() + geom_smooth()
```

```{r two-discrete-variables}

# Saving a plot base
two_discrete <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, fill = sex))

# Bar plot
two_discrete + geom_bar()

# Bar plot side by side
two_discrete + geom_bar(position = position_dodge())


```

# Discrete and continuous variables in same plot

```{r discrete-continuous-variables}

two_mixed <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, y = bmi))

# Boxplot
two_mixed + geom_boxplot()

# Jitter plot to se the individial data points
two_mixed + geom_jitter()

# Violin plot
two_mixed + geom_violin()


```

# Exercise to make plots with one or two variables

```{r exercise}

# 1a. Distribution of age
ggplot(nhanes_tidied, aes(x = age)) +
    geom_histogram()
    
# 1b. Distribution of age of diabetes diagnosis
ggplot(nhanes_tidied, aes(x = diabetes_age)) +
    geom_histogram()

# 2a. Number of people who smoke now
ggplot(nhanes_tidied, aes(x = smoke_now)) +
    geom_bar()

# 2b. Number of people who are physically active
ggplot(nhanes_tidied, aes(x = phys_active)) +
    geom_bar()

# 3a. BMI in relation to systolic blood pressure
ggplot(nhanes_tidied, aes(x = bmi, y = bp_sys_ave)) +
    geom_hex()

# 3b. BMI relation to diastolic blood pressure
ggplot(nhanes_tidied, aes(x = bmi, y = bp_dia_ave)) +
    geom_hex()
    
# 4. Physically active people with or without diabetes
ggplot(nhanes_tidied, aes(x = diabetes, fill = phys_active)) +
    geom_bar(position = position_dodge())

# 5. Poverty levels between those with or without diabetes. Smaller numbers means higher poverty.
ggplot(nhanes_tidied, aes(x = diabetes, y = poverty)) +
    geom_violin()

```



